name: chucker_flutter
description: Chucker Flutter helps you inspect the HTTP(S) requests/responses. It stores data locally and provides a UI for inspecting network calls and sharing their content.
version: 1.0.0+1
homepage: https://github.com/syedmurtaza108/chucker-flutter

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  share_plus: ^4.0.1
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0