name: chucker_flutter
description: Chucker Flutter helps you inspect the HTTP(S) requests/responses. It stores data locally and provides a UI for inspecting network calls and sharing their content.
version: 1.4.1
repository: https://github.com/syedmurtaza108/chucker-flutter
issue_tracker: https://github.com/syedmurtaza108/chucker-flutter/issues
funding:
  - https://www.patreon.com/syedmurtaza

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  chopper: ^5.1.0
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  http_mock_adapter: ^0.3.2
  share_plus: ^6.3.0
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0